---

  - name: Add prometheus helm repository
    kubernetes.core.helm_repository:
      name: prometheus
      repo_url: https://prometheus-community.github.io/helm-charts

  - name: Deploy kube-prometheus-stack chart
    kubernetes.core.helm:
      name: kube-prometheus-stack
      chart_ref: prometheus/kube-prometheus-stack
      release_namespace: "{{ monitoring_ns }}"
      create_namespace: yes
      wait: yes
      values:
        alertmanager:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "{{ issuer_name }}"
            ingressClassName: nginx
            tls:
            - secretName: "{{ issuer_name }}-tls"
              hosts:
              - "{{ alertmanager_subdomain }}.{{ domain }}"
            hosts:
            - "{{ alertmanager_subdomain }}.{{ domain }}"
            paths:
            - /
            pathType: Prefix
        grafana:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "{{ issuer_name }}"
            ingressClassName: nginx
            tls:
            - secretName: "{{ issuer_name }}-tls"
              hosts:
              - "{{ grafana_subdomain }}.{{ domain }}"
            hosts:
            - "{{ grafana_subdomain }}.{{ domain }}"
            paths:
            - /
            pathType: Prefix
        prometheus:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: "{{ issuer_name }}"
            ingressClassName: nginx
            tls:
            - secretName: "{{ issuer_name }}-tls"
              hosts:
              - "{{ prometheus_subdomain }}.{{ domain }}"
            hosts:
            - "{{ prometheus_subdomain }}.{{ domain }}"
            paths:
            - /
            pathType: Prefix
