---

  - name: Create pihole build directory
    file:
      path: /build/pihole
      state: directory

  - name: Add pihole helm repository
    kubernetes.core.helm_repository:
      name: pihole
      repo_url: https://mojo2600.github.io/pihole-kubernetes

  - name: Deploy pihole chart
    kubernetes.core.helm:
      name: pihole
      chart_ref: pihole/pihole
      release_namespace: pihole
      create_namespace: true
      values:
        adminPassword: "{{ pihole_pwd }}"
        dnsmasq:
          customDnsEntries:
            - address=/nas/192.168.178.10
            - address=/test/192.168.178.10
          customCnameEntries:
            - cname=foo.nas,nas
        persistentVolumeClaim:
          enabled: true
        serviceDns:
          loadBalancerIP: "{{ pihole_ip }}"
          type: LoadBalancer
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
        extraEnvVars:
          TZ: "{{ pihole_timezone }}"

  - name: Copy manifest files to target
    template:
      src: "{{ item }}"
      dest: /build/pihole/
    with_fileglob:
    - "templates/*.yml.j2"
    vars:
      gdrive_serviceaccount: "{{ lookup('template','files/gdrive-serviceaccount.json') | string | regex_replace('[\\r\\n\\t]+','') | b64encode }}"

  - name: Apply pihole ingress manifest
    command: kubectl apply -f /build/pihole/pihole-ingress.yml.j2
    retries: 3
    delay: 10
    register: result
    until: result is not failed

  - name: Apply pihole backup manifest
    command: kubectl apply -f /build/pihole/pihole-backup.yml.j2
    retries: 3
    delay: 10
    register: result
    until: result is not failed
