---

- name: Destroy primary node
  hosts: primary
  become: yes
  roles:
    - { role: destroy/primary, tags: destroy-primary }

- name: Destroy worker nodes
  hosts: worker
  become: yes
  roles:
    - { role: destroy/worker, tags: destroy-worker }

  tasks:
  - name: Destroy complete
    debug:
      msg: "RPi Home Server has been destroyed!"
