---

- name: Default "pi" account password reset playbook
  hosts: all
  become: yes

  vars_prompt:
    - name: "pi_pwd"
      prompt: "New pi account password"
      default: "default"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes

  tasks:
  - name: Set a new password for the default "pi" account
    user:
      name: "pi"
      password: "{{ pi_pwd }}"
