---
  - name: Reboot host
    command: shutdown -r +0
    async: 0
    poll: 0
    ignore_errors: true
    become: true

  - name: Wait for host to reboot
    wait_for_connection: timeout=300 delay=5
