---

  - name: Add nginx ingress helm repository
    kubernetes.core.helm_repository:
      name: ingress-nginx
      repo_url: https://kubernetes.github.io/ingress-nginx

  - name: Deploy nginx ingress chart
    kubernetes.core.helm:
      name: ingress-nginx
      chart_ref: ingress-nginx/ingress-nginx
      release_namespace: "{{ nginx_ns }}"
      create_namespace: yes
      wait: yes
      values:
        defaultBackend:
          enabled: false
