---

  - name: Add nextcloud helm repository
    kubernetes.core.helm_repository:
      name: nextcloud
      repo_url: https://nextcloud.github.io/helm

  - name: Deploy nextcloud chart
    kubernetes.core.helm:
      name: nextcloud
      chart_ref: nextcloud/nextcloud
      release_namespace: "{{ cloud_ns }}"
      create_namespace: yes
      wait: yes
      values:
        nextcloud:
          host: "{{ cloud_subdomain }}.{{ domain }}"
          username: "admin"
          password: "default"
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
            cert-manager.io/cluster-issuer: "{{ issuer_name }}"
          className: nginx
          tls:
          - secretName: "{{ issuer_name }}-tls"
            hosts:
            - "{{ cloud_subdomain }}.{{ domain }}"
          hosts:
          - "{{ cloud_subdomain }}.{{ domain }}"
          paths:
          - /
          pathType: Prefix



  # - name: Add bitnami helm repository
  #   kubernetes.core.helm_repository:
  #     name: bitnami
  #     repo_url: https://charts.bitnami.com/bitnami

  # - name: Deploy owncloud chart
  #   kubernetes.core.helm:
  #     name: owncloud
  #     chart_ref: bitnami/owncloud
  #     release_namespace: "{{ cloud_ns }}"
  #     create_namespace: yes
  #     wait: yes
  #     values:
  #       owncloudHost: test
  #       owncloudPassword: default
  #       mariadb:
  #         auth:
  #           rootPassword: default
  #           password: default
  #       service:
  #         type: ClusterIP
  #       ingress:
  #         annotations:
  #           cert-manager.io/cluster-issuer: "{{ issuer_name }}"
  #         ingressClassName: nginx
  #         tls:
  #         - secretName: "{{ issuer_name }}-tls"
  #           hosts:
  #           - "{{ cloud_subdomain }}.{{ domain }}"
  #         hosts:
  #         - "{{ cloud_subdomain }}.{{ domain }}"
  #         paths:
  #         - /
  #         pathType: Prefix
